import { EdgeStoreProvider } from '@/lib/edgestore'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h2> ---- Olá, para realizar o envio por favor insira seu PDF, e a url da sua imagem de capa! Para mais informações entre em contato direto conosco pelo email:indietora@gmail.com ou pelo fone:53 9 9988-7766! Obrigada! ^^ ---</h2>
        <EdgeStoreProvider>{children}</EdgeStoreProvider>
      </body>
    </html>
  )
}
